# примеры API-запросов

@baseUrl = http://127.0.0.1:5000

# создание объявления
POST {{baseUrl}}/market/
Content-Type: application/json

{
  "title": "Garage sale",
  "description": "Garage for sale in excellent condition",
  "owner": "Alex"
}

###

# получение объявления
GET {{baseUrl}}/market/1
Content-Type: application/json


###
# удаление объявления
DELETE {{baseUrl}}/market/1
Content-Type: application/json
